name: Push files from development repository to production repository

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message'
        required: true
        default: 'Enter commit message here'

jobs:
  pushFiles:
    runs-on: ubuntu-latest

    steps:
      - name: Check out development repository
        uses: actions/checkout@v3

      - name: Check out production repository
        uses: actions/checkout@v3
        with:
          repository: CITIES-Dashboard/citiesdashboard.com
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
          path: ./prod-files

      - name: Copy files from development repository to production repository
        run: rsync -av --exclude=.git/ --exclude=.github/workflows/ --exclude=.vscode --exclude=documentation/ --exclude=.gitignore --exclude=readme.md --exclude=prod-files/ ./ ./prod-files

      - name: Commit and push changes to production repository
        run: |
          cd ./prod-files
          git config user.name ${{ secrets.USER_NAME }}
          git config user.email ${{ secrets.USER_EMAIL }}
          git add .
          git commit -m "${{ github.event.inputs.commit_message }}"
          git push origin main
